# Generated by Django 2.1.8 on 2019-05-02 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('entryDate', models.DateField()),
                ('productURL', models.URLField()),
                ('productdescription', models.TextField()),
            ],
            options={
                'db_table': 'techproduct',
            },
        ),
        migrations.CreateModel(
            name='TechReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewtitle', models.CharField(max_length=255)),
                ('reviewdate', models.DateTimeField()),
                ('reviewrating', models.SmallIntegerField()),
                ('reviewText', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techapp.TechProduct')),
                ('reviewers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'techreview',
            },
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=255)),
                ('typedescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='techproduct',
            name='techtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='techapp.TechType'),
        ),
        migrations.AddField(
            model_name='techproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
